print('hello world')
print('have a nice day')
Nama = str(input('Nama:  '))
Hobi = str(input('Hobi:  '))
Umur = int(input('Umur:  '))
Prodi = str(input('Prodi: '))
print('--------------------------')
print('Nama;  ',Nama)
print('Hobi:  ',Hobi)
print('Umur:  ',Umur)
print('Prodi: ',Prodi)
